#pragma once
enum CurrentMenu {
    FRONT_OF_HOUSE,
    FRONT_OF_HOUSE_PROCESS,
    KITCHEN_STAFF,
    MAIN_MENU,
    ORDER_MENU,
    DRINK_MENU,
    EDITOR,
    TABLE_EDITOR,
    MENU_EDITOR,
    TABLE_EDITOR_PROCESS,
    MENU_EDITOR_PROCESS,
};